### ISSUE TITLE
Add `or` function in chain

### ISSUE THREAD

**Issue by cbchouinard** [design-systems/regimen#4]
Something like this could be useful for more consumption tolerant section: 

`$.expect(block).typeOf(“quote”).or.with.a("description").length.greaterThan(150)`

To simplify thing, or could always refer back to the expect data and not cover case like this for now: 

`$.expect(block).with.a("description").length.greaterThan(150).or.lessThan(50)`

**Comment by paulyoung** [comment]
This was discussed in #7.
