### ISSUE TITLE
Can we add support for `.or`?

### ISSUE THREAD

**Issue by paulyoung** [design-systems/regimen#7]
e.g.

``` coffeescript
expect(block).subtypeOf("text").or.subtypeOf("media")
```

**Comment by paulyoung** [comment]
It seems that `.or` can't be supported because an `AssertionError` is (potentially) thrown before we ever reach `.or` and any following assertions.

**Comment by bergie** [comment]
Flowerflip 0.2.3 recognizes quotes as both `media` and `textual`

**Comment by paulyoung** [comment]
0.2.3 used in https://github.com/the-grid/taylor/commit/8c7cb3d6875f02aa1a4e43a8d1614f18b436ecdd
